version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: auth_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./internal/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - auth
  php:
    build:
      context: .
      dockerfile: ./internal/php/Dockerfile
    container_name: auth_php
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    ports:
      - "9090:9000"
    networks:
      - auth
  mysql:
    image: mysql:8.0.20
    container_name: auth_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - auth
networks:
  auth:
    driver: bridge